puppetlabs/courseware-lms-content

courses/01-puppet/rspec_outline_notes.md
=> copying template to begin development for rspec plw course

courses/01-puppet/01_2xxx_code_test.md, courses/01-puppet/01_2xxx_intro_test_puppet.md
Ready for review by primary SME, Klynton. 
Please see and review with Captivate file on box: Education->LMS_Online_Courses->Course_Development->01-Puppet->TestingBundle->01_2xxx_intro_test_puppet.cptx
https://puppetlabs.app.box.com/files/0/f/3044288649/TestingBundle
=> intro to test draft for review

courses/01-puppet/01_2xxx_intro_test_puppet.md
first lesson - Intro - was reviewed. added the module writing and structure review slides to this lesson. Ready for review by SME.
=> combined first two testing lessons

courses/01-puppet/01_2xxx_intro_test_puppet.md
Klynton - ready for review. This is the re-worked Introduction to Testing Puppet Code. You can see the published Captivate files, with the computer generated voice, on Box: Education->LMS_OnlineCourses->01-Puppet->TestingBundle->Intro_Puppet_Test.
=> Ready for Review 

courses/01-puppet/01_2xxx_intro_test_puppet.md
=> removed duplicate text

courses/01-puppet/intro_test_puppet.md
=> final edits to the course - added resources, deleted one line.

modules/ssh/.fixtures.yml, modules/ssh/Rakefile, modules/ssh/files/Debian-client, modules/ssh/files/Debian-server, modules/ssh/files/RedHat-client, modules/ssh/files/RedHat-server, modules/ssh/manifests/client.pp, modules/ssh/manifests/init.pp, modules/ssh/manifests/params.pp, modules/ssh/manifests/server.pp, modules/ssh/spec/classes/ssh_spec.rb, modules/ssh/spec/spec_helper.rb, modules/ssh/tests/client.pp, modules/ssh/tests/init.pp, modules/ssh/tests/server.pp
This should work on both RedHat and Debian based machines.
=> Adding the ssh module for testing.

modules/lms/files/default/hiera.yaml, modules/lms/files/default/hieradata/common.yaml, modules/lms/files/hiera/hiera.yaml, modules/lms/files/hiera/hieradata/common.yaml, modules/lms/manifests/init.pp, modules/lms/tests/autoloading.pp, modules/lms/tests/classes.pp, modules/lms/tests/cli_intro.pp, modules/lms/tests/code.pp, modules/lms/tests/default.pp, modules/lms/tests/facter_intro.pp, modules/lms/tests/hiera.pp, modules/lms/tests/hiera_intro.pp, modules/lms/tests/inheritance.pp, modules/lms/tests/module.pp, modules/lms/tests/puppet_lint.pp, modules/lms/tests/relationships.pp, modules/lms/tests/resources.pp, scripts/course_selector.rb
Provides a way of setting up the LMS environment for a specific course.
The course_selector.rb script can be installed on the LMS vms and run to select the enviornment.
Everything is set to "default" files right now except the OILT hiera course.
=> Course scripts

courses/puppet/smoke_test.md
=> Test smoke

courses/puppet/smoke_test.md
For review by Klynton - initial commit for smoke test .md file
=> For review by Klynton - Smoke testing

courses/puppet/intro_test_puppet.md
Edits to the testing intro class to update screen shots for TR.
=> Ready for Review by Klynton

courses/puppet/smoke_test.md
please merge - fixed file smoke testing
=> fixing merge conflict

courses/puppet/code_test.md, modules/ntplint/manifests/init.pp
@klynton please review and merge - minor audio edits; also edited the file for the practice exercise with parser and lint
=> Test validcode - @klynton

courses/puppet/smoke_test.md, modules/ssh/ssh_solutions/client.pp, modules/ssh/ssh_solutions/init.pp, modules/ssh/ssh_solutions/params.pp, modules/ssh/ssh_solutions/server.pp
No content changes - but moved the audio around a little to match the slide content.
=> Smoke Tests edits - ready for review by Clinton

modules/lms/tests/hiera.pp
Do this for now.
I made an epic for refactoring this in the future:
https://tickets.puppetlabs.com/browse/TRAINTECH-141
=> create environments dir for hiera course

courses/puppet/rspec_puppet_unit_tests.md
=> Unit tests - Ready for Review by Klynton

modules/lms/files/parser/example_modules/data_types/examples/block_resource.pp, modules/lms/files/parser/example_modules/data_types/examples/conditionals.pp, modules/lms/files/parser/example_modules/data_types/examples/parameters.pp, modules/lms/files/parser/example_modules/data_types/examples/validation.pp, modules/lms/files/parser/example_modules/data_types/manifests/block_resource.pp, modules/lms/files/parser/example_modules/data_types/manifests/params.pp, modules/lms/files/parser/example_modules/data_types/manifests/validation.pp, modules/lms/files/parser/example_modules/iterating/examples/each.pp, modules/lms/files/parser/example_modules/iterating/examples/functions.pp, modules/lms/files/parser/example_modules/iterating/manifests/each.pp, modules/lms/files/parser/example_modules/iterating/manifests/functions.pp, modules/lms/manifests/course/parser.pp, modules/lms/tests/parser.pp, scripts/course_menu.rb.erb
=> Future parser/courses 1151

modules/ssh/manifests/client.pp, modules/ssh/manifests/server.pp
These files include intention errors. They are located: /courseware-lms-content/tree/master/modules/ssh
The correct solution files are located in: /courseware-lms-content/tree/master/modules/ssh/ssh_solutions
=> Ready for review: exercise files for the smoke test practice exercises.

scripts/course_selector.rb, scripts/course_update.rb, scripts/update.pp
=> Better update behavior for course_selector

modules/lms/files/unit_test/problem_modules/ssh/.fixtures.yml, modules/lms/files/unit_test/problem_modules/ssh/Rakefile, modules/lms/files/unit_test/problem_modules/ssh/examples/client.pp, modules/lms/files/unit_test/problem_modules/ssh/examples/init.pp, modules/lms/files/unit_test/problem_modules/ssh/examples/server.pp, modules/lms/files/unit_test/problem_modules/ssh/files/client, modules/lms/files/unit_test/problem_modules/ssh/files/server, modules/lms/files/unit_test/problem_modules/ssh/manifests/client.pp, modules/lms/files/unit_test/problem_modules/ssh/manifests/init.pp, modules/lms/files/unit_test/problem_modules/ssh/manifests/params.pp, modules/lms/files/unit_test/problem_modules/ssh/manifests/server.pp, modules/lms/files/unit_test/problem_modules/ssh/serverspec/Rakefile, modules/lms/files/unit_test/problem_modules/ssh/serverspec/spec/localhost/ssh_spec.rb, modules/lms/files/unit_test/problem_modules/ssh/serverspec/spec/spec_helper.rb, modules/lms/files/unit_test/problem_modules/ssh/spec/classes/ssh_spec.rb, modules/lms/files/unit_test/problem_modules/ssh/spec/spec_helper.rb, modules/lms/files/unit_test/problem_modules/ssh/ssh_solutions/client.pp, modules/lms/files/unit_test/problem_modules/ssh/ssh_solutions/init.pp, modules/lms/files/unit_test/problem_modules/ssh/ssh_solutions/params.pp, modules/lms/files/unit_test/problem_modules/ssh/ssh_solutions/server.pp
Ready for review @klynton 
adding practice files. PLEASE NOTE: Intentional errors in the files
=> creating unit testing practice files

courses/puppet/smoke_test.md
ready for review @klynton - changed path - replaced puppet with code.
=> fixed paths in smoke test course

courses/puppet/rspec_puppet_unit_tests.md
Please review. Although @klynton  has been the reviewer for this course, I think this quiz can be reviewed by anyone who has familiarity with rspec-puppet
=> quiz for unit testing course

courses/products/what_is_pe.md, courses/puppet/classes.md, courses/puppet/resources.md, courses/puppet/what_is_puppet.md
=> added transcript to What is Puppet course

courses/published/intros/getting_started_with_hiera.md
Uses the same name as the course Markdown file found in the parent directory
=> Created new directory to house course intro text

courses/published/css/selfpaced.css
These are actually what's currently on the site for the beta test of the hiera course, but I wanted to make sure I updated the repo.
=> More specific selectors in css

courses/published/get_hiera_1.md, courses/published/get_hiera_2.md, courses/published/get_hiera_3.md, courses/published/get_hiera_4.md, courses/published/get_hiera_5.md, courses/published/rendered/get_hiera_1.html, courses/published/rendered/get_hiera_2.html, courses/published/rendered/get_hiera_3.html, courses/published/rendered/get_hiera_4.html, courses/published/rendered/get_hiera_5.html
These are already released for the beta, this just updates the source
=> Typo fixes and default hiera.yaml dir change

courses/published/introduction_to_the_linux_command_line.md
This replaces the video that needed to be rebranded, with a very basic
lesson and reference to linuxjourney.com.
=> Update intro to the CLI

courses/published/testing_puppet_validating_your_code.md
This video included about 5min of out of scope content. Narrowed the focus and updated the quiz to focus on relevant content.
=> Removed out of scope content from validating

_lmscontent/example_component/metadata.json
PRTNRENBLE-229 #resolved #time 1h
This is an example of what a learning component directory should
look like for the new deployment tooling.
=> (PRTNRENBLE-229) New LMS Content Example

_lmscontent/example_component/metadata.json
New example of the JSON needed to create a learning component,
as provided by LD Support
=> (MAINT) New JSON Example

course_outlines/configuration_management/deploy_code.md
The objectives for the lesson-at-large are at a place where I am
satisfied with it. Next step would be work on the details, and fleshing
out the Objectives, Sub-topics etc.
COURSES-3329 #start-progress #time 3h Total work logged
=> (WIP) Curriculum form - 'deploy code and run the agent'

video/manifest_classes_LVM.md
@kjhenner take a look and see what you think. Thanks!
=> Updated quest to sound like a script

video/package_file_service_LVM.md
I kept some 2nd person pronouns here where I thought they helped the viewer. Feel free, of course, to overrule that.
=> Edited script for PFS

_lmscontent/_tasks/README.md
This README update requires #173
=> Add notes about running on laptop

course_outlines/configuration_management/declarative_structure_Puppet_architecture.md
Added new information based on a meeting with the elearning team
@greglarkin can you please review, make any needed changes, and then merge? I trust whatever you come up with, and I would like to solidify this so we can start piecing it together.
=> Updated course outline and description

_lmscontent/how_to_use_this_course/content.md
what do you think of this as an alternative to the embedded GIF?
=> Added a link to the GIF, removed iframe

_lmscontent/getting_started_with_hiera/part_1/content.md, _lmscontent/getting_started_with_hiera/part_2/content.md, _lmscontent/getting_started_with_hiera/part_3/content.md, _lmscontent/getting_started_with_hiera/part_4/content.md
TRAINLMS-425 #resolved #time 2h
This removes the custom CSS that was added to the course header,
but does not remove most of the custom DOM that was built.
=> (TRAINLMS-415) Restyle Getting Started With Hiera

_lmscontent/syntax_and_package_installation/content.md
@greglarkin , what do you think of the rearrangement and additional text? I wanted to let users know that they were on their own after awhile. I also removed a hyphen from a compound adverb.
=> Additional help for students

_lmscontent/facts/what_are_they?/content.md
Do we need to discuss the structure of this syntax--the { } and the $ ? It may be that we don't but I wanted to check. It seems like we should remind them of what they learned in resources and how it is applied here, if possible. If not, cool. Also, we are using { } here, but the docs say to only use it for double interpolation. I may be reading this whole thing wrong :) but looking for clarity on reminding users about any language basics they should look out for. Again, it may be that none exist
=> Question on $

_lmscontent/configuring_a_service/content.md
I reworded sections to call out the attribute where the information needed to go. I wanted to reinforce the lessons from Anatomy of a Resource. Is this technically accurate?
=> Reworded tasks for clarity

_lmscontent/README.md
@greglarkin Let me know if these look accurate, and please edit as needed.
=> updated readme for simplified push to production step-by-step process

_lmscontent/orchestration_tasks/tasks/content.md
Improved the content of the alt text to be more descriptive; moved the PQL Query image to come after the description to match the formatting used for other explanatory images.
=> Improved alt text; moved "PQL Query" image

_lmscontent/orchestration_tasks/tasks/content.md
Resized screenshots to 75% width and height and changed links to HTML instead of markdown
=> Resized screenshots; changed links to HTML

_lmscontent/puppet_language_basics/resources-anatomy_of_a_resource/content.md
Changed owner => 'root', group => 'root'
=> Updated Anatomy of a Resource image

_lmscontent/discovery/content.md
@greglarkin Can you give this a good look?
=> ran rake:migrate markdown

course_development_kit/1_StartHere_JobStory.md, course_development_kit/2_DesignStrategy.md
This is a WIP but ready to be merged so we can work on this as a team. This folder does not get pushed to sandbox or production.
=> Added course dev kit folders

_lmspublic_pages/README.md, _lmspublic_pages/pages/course-catalog.html, _lmspublic_pages/staticfiles/skin/lde-skin-puppetlabs/lde-skin.css
TRAINTECH-1633 #resolved #time 4d
This is the newly designed course catalog and updated skin.css file
that it requires. The redesign removes course summaries, adds in
duration, tags, and logos, and significantly shrinks the vertical space
that each course occupies. Courses that do not cost anything now have a
green button and text that says "free."
This will improve the UX in making more courses visible at once, with
relevant but short info right there.
Adding the styling to lde-skin.css allows this to be reused across other
public facing pages.
=> (TRAINTECH-1633) Redesigned Course Catalog
